import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
const file = process.argv[2]!;
const t = new StdioClientTransport({ command: 'npx', args: ['tsx', 'src/cli.ts', 'mcp', '--gate', 'https://lading.167-233-221-236.sslip.io'], env: { ...process.env as Record<string, string>, LADING_X402_KEY_FILE: process.env.HOME + '/.lading/x402.key', LADING_MAX_USDC_PER_CALL: '1' }, stderr: 'inherit' });
const c = new Client({ name: 'drive', version: '0' });
await c.connect(t);
const pick = (r: any) => JSON.parse(r.content[0].text);
const w0 = pick(await c.callTool({ name: 'lading_wallet', arguments: {} }));
console.log('wallet before', w0.usdcOnBase);
const lk = pick(await c.callTool({ name: 'lading_lookup', arguments: { path: file } }));
console.log('lookup', JSON.stringify(lk).slice(0, 200));
const q = pick(await c.callTool({ name: 'lading_quote', arguments: { path: file } }));
console.log('quote', JSON.stringify({ parts: q.parts, total: q.total }));
const t0 = Date.now();
const p = pick(await c.callTool({ name: 'lading_put', arguments: { path: file, name: 'four-mib.bin' } }));
console.log('put', Math.round((Date.now() - t0) / 1000), 's', JSON.stringify({ reused: p.reused, parts: p.parts, legs: (p.legs ?? []).map((l: any) => [l.network, l.id, l.parts?.length]), tx: p.manifestTxId, name: p.name?.name, toon: p.toon, multipart: p.multipart, x402: p.x402, error: p.error }));
if (p.isError) console.log('ERROR', JSON.stringify(p));
const w1 = pick(await c.callTool({ name: 'lading_wallet', arguments: {} }));
console.log('wallet after', w1.usdcOnBase);
await c.close();
